// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bo} from '../models';

export function CreateAdapter(arg1:bo.CreateAdapterReq):Promise<bo.SimpleResp>;

export function DeleteAdapter(arg1:number):Promise<bo.SimpleResp>;

export function GetAdapter(arg1:number):Promise<bo.GetAdapterResp>;

export function SearchAdapters(arg1:bo.SearchAdapterReq):Promise<bo.SearchAdapterResp>;

export function UpdateAdapter(arg1:bo.UpdateAdapterReq):Promise<bo.SimpleResp>;
