// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAdapter(arg1) {
  return window['go']['service']['Adapter']['CreateAdapter'](arg1);
}

export function DeleteAdapter(arg1) {
  return window['go']['service']['Adapter']['DeleteAdapter'](arg1);
}

export function GetAdapter(arg1) {
  return window['go']['service']['Adapter']['GetAdapter'](arg1);
}

export function SearchAdapters(arg1) {
  return window['go']['service']['Adapter']['SearchAdapters'](arg1);
}

export function UpdateAdapter(arg1) {
  return window['go']['service']['Adapter']['UpdateAdapter'](arg1);
}
