// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Install(arg1) {
  return window['go']['service']['AppStore']['Install'](arg1);
}

export function SearchApps(arg1) {
  return window['go']['service']['AppStore']['SearchApps'](arg1);
}
