// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bo} from '../models';

export function Install(arg1:string):Promise<bo.SimpleResp>;

export function SearchApps(arg1:bo.AppFilter):Promise<bo.AppList>;
