// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bo} from '../models';

export function CreateCategory(arg1:bo.CreateCategoryReq):Promise<bo.SimpleResp>;

export function DeleteCategory(arg1:number):Promise<bo.SimpleResp>;

export function GetCategory(arg1:number):Promise<bo.GetCategoryResp>;

export function SearchCategoryList(arg1:bo.SearchCategoryReq):Promise<bo.SearchCategoryResp>;

export function UpdateCategory(arg1:bo.UpdateCategoryReq):Promise<bo.SimpleResp>;
