// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1) {
  return window['go']['service']['Category']['CreateCategory'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['service']['Category']['DeleteCategory'](arg1);
}

export function GetCategory(arg1) {
  return window['go']['service']['Category']['GetCategory'](arg1);
}

export function SearchCategoryList(arg1) {
  return window['go']['service']['Category']['SearchCategoryList'](arg1);
}

export function UpdateCategory(arg1) {
  return window['go']['service']['Category']['UpdateCategory'](arg1);
}
