// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCityList() {
  return window['go']['service']['Common']['GetCityList']();
}

export function GetMenuItems() {
  return window['go']['service']['Common']['GetMenuItems']();
}

export function OpenFileDialog() {
  return window['go']['service']['Common']['OpenFileDialog']();
}

export function ToJsonSchema(arg1) {
  return window['go']['service']['Common']['ToJsonSchema'](arg1);
}
