// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bo} from '../models';

export function GetCityList():Promise<Array<bo.City>>;

export function GetMenuItems():Promise<bo.MenuItem>;

export function OpenFileDialog():Promise<bo.SimpleResp>;

export function ToJsonSchema(arg1:{[key: string]: any}):Promise<bo.SimpleResp>;
