// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCompany(arg1, arg2) {
  return window['go']['service']['Company']['CreateCompany'](arg1, arg2);
}

export function DeleteCompany(arg1) {
  return window['go']['service']['Company']['DeleteCompany'](arg1);
}

export function GetCompany(arg1) {
  return window['go']['service']['Company']['GetCompany'](arg1);
}

export function SearchCompanyList(arg1) {
  return window['go']['service']['Company']['SearchCompanyList'](arg1);
}

export function UpdateCompany(arg1, arg2, arg3) {
  return window['go']['service']['Company']['UpdateCompany'](arg1, arg2, arg3);
}
