// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Call(arg1, arg2, arg3) {
  return window['go']['service']['Datastore']['Call'](arg1, arg2, arg3);
}

export function CreateData(arg1, arg2) {
  return window['go']['service']['Datastore']['CreateData'](arg1, arg2);
}

export function CreateDatastore(arg1) {
  return window['go']['service']['Datastore']['CreateDatastore'](arg1);
}

export function CreateMapping(arg1) {
  return window['go']['service']['Datastore']['CreateMapping'](arg1);
}

export function DelBinding(arg1, arg2) {
  return window['go']['service']['Datastore']['DelBinding'](arg1, arg2);
}

export function DeleteDatastore(arg1) {
  return window['go']['service']['Datastore']['DeleteDatastore'](arg1);
}

export function GetBindingData(arg1, arg2) {
  return window['go']['service']['Datastore']['GetBindingData'](arg1, arg2);
}

export function GetData(arg1, arg2) {
  return window['go']['service']['Datastore']['GetData'](arg1, arg2);
}

export function GetDatastore(arg1) {
  return window['go']['service']['Datastore']['GetDatastore'](arg1);
}

export function GetDatastoreMenus(arg1) {
  return window['go']['service']['Datastore']['GetDatastoreMenus'](arg1);
}

export function GetMapping(arg1) {
  return window['go']['service']['Datastore']['GetMapping'](arg1);
}

export function GetSheetData(arg1) {
  return window['go']['service']['Datastore']['GetSheetData'](arg1);
}

export function ImportData(arg1, arg2, arg3, arg4) {
  return window['go']['service']['Datastore']['ImportData'](arg1, arg2, arg3, arg4);
}

export function SearchBindingAdapters(arg1) {
  return window['go']['service']['Datastore']['SearchBindingAdapters'](arg1);
}

export function SearchData(arg1) {
  return window['go']['service']['Datastore']['SearchData'](arg1);
}

export function SearchDatastoreList(arg1) {
  return window['go']['service']['Datastore']['SearchDatastoreList'](arg1);
}

export function SearchMapping(arg1) {
  return window['go']['service']['Datastore']['SearchMapping'](arg1);
}

export function SetBinding(arg1, arg2, arg3) {
  return window['go']['service']['Datastore']['SetBinding'](arg1, arg2, arg3);
}

export function SetSheetData(arg1, arg2) {
  return window['go']['service']['Datastore']['SetSheetData'](arg1, arg2);
}

export function UpdateData(arg1, arg2, arg3) {
  return window['go']['service']['Datastore']['UpdateData'](arg1, arg2, arg3);
}

export function UpdateDatastore(arg1) {
  return window['go']['service']['Datastore']['UpdateDatastore'](arg1);
}

export function UpdateDatastoreSchema(arg1) {
  return window['go']['service']['Datastore']['UpdateDatastoreSchema'](arg1);
}

export function UpdateMapping(arg1) {
  return window['go']['service']['Datastore']['UpdateMapping'](arg1);
}
