// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bo} from '../models';

export function Call(arg1:number,arg2:string,arg3:Array<number>):Promise<bo.SimpleResp>;

export function CreateData(arg1:number,arg2:{[key: string]: any}):Promise<bo.SimpleResp>;

export function CreateDatastore(arg1:bo.CreateDatastoreReq):Promise<bo.SimpleResp>;

export function CreateMapping(arg1:bo.CreateMappingReq):Promise<bo.SimpleResp>;

export function DelBinding(arg1:number):Promise<bo.SimpleResp>;

export function DeleteDatastore(arg1:number):Promise<bo.SimpleResp>;

export function GetBindingData(arg1:number,arg2:number):Promise<bo.MapResp>;

export function GetData(arg1:number,arg2:number):Promise<bo.Row>;

export function GetDatastore(arg1:number):Promise<bo.GetDatastoreResp>;

export function GetDatastoreMenus(arg1:number):Promise<bo.MenuResp>;

export function GetMapping(arg1:number):Promise<bo.GetMappingResp>;

export function GetSheetData(arg1:number):Promise<bo.Sheet>;

export function ImportData(arg1:number,arg2:string,arg3:string,arg4:string):Promise<bo.SimpleResp>;

export function SearchData(arg1:bo.SearchDataReq):Promise<bo.SearchDataResp>;

export function SearchDatastoreList(arg1:bo.SearchDatastoreReq):Promise<bo.SearchDatastoreResp>;

export function SearchMapping(arg1:number):Promise<bo.SearchMappingResp>;

export function SetBinding(arg1:number,arg2:number,arg3:{[key: string]: any}):Promise<bo.SimpleResp>;

export function SetSheetData(arg1:number,arg2:{[key: string]: any}):Promise<bo.SimpleResp>;

export function UpdateData(arg1:number,arg2:number,arg3:{[key: string]: any}):Promise<bo.SimpleResp>;

export function UpdateDatastore(arg1:bo.UpdateDatastoreReq):Promise<bo.SimpleResp>;

export function UpdateDatastoreSchema(arg1:bo.UpdateDatastoreSchemaReq):Promise<bo.SimpleResp>;

export function UpdateMapping(arg1:bo.UpdateMappingReq):Promise<bo.SimpleResp>;
