// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProduct(arg1) {
  return window['go']['service']['Product']['CreateProduct'](arg1);
}

export function DiscontinuedConfirm(arg1) {
  return window['go']['service']['Product']['DiscontinuedConfirm'](arg1);
}

export function DiscontinuedProduct(arg1, arg2) {
  return window['go']['service']['Product']['DiscontinuedProduct'](arg1, arg2);
}

export function GetProductDetail(arg1) {
  return window['go']['service']['Product']['GetProductDetail'](arg1);
}

export function LaunchProduct(arg1, arg2) {
  return window['go']['service']['Product']['LaunchProduct'](arg1, arg2);
}

export function LaunchedConfirm(arg1, arg2) {
  return window['go']['service']['Product']['LaunchedConfirm'](arg1, arg2);
}

export function SearchProductList(arg1) {
  return window['go']['service']['Product']['SearchProductList'](arg1);
}

export function UpdateProduct(arg1, arg2) {
  return window['go']['service']['Product']['UpdateProduct'](arg1, arg2);
}
