// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bo} from '../models';

export function CreateProduct(arg1:bo.CreateProductReq):Promise<bo.SimpleResp>;

export function DiscontinuedConfirm(arg1:number):Promise<bo.SimpleResp>;

export function DiscontinuedProduct(arg1:number,arg2:number):Promise<bo.SimpleResp>;

export function GetProductDetail(arg1:number):Promise<bo.GetDetailResp>;

export function LaunchProduct(arg1:number,arg2:number):Promise<bo.SimpleResp>;

export function LaunchedConfirm(arg1:number,arg2:string):Promise<bo.SimpleResp>;

export function SearchProductList(arg1:bo.SearchProductReq):Promise<bo.SearchProductResp>;

export function UpdateProduct(arg1:number,arg2:number):Promise<bo.SimpleResp>;
