// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateStore(arg1, arg2) {
  return window['go']['service']['Store']['CreateStore'](arg1, arg2);
}

export function DeleteStore(arg1) {
  return window['go']['service']['Store']['DeleteStore'](arg1);
}

export function GetStore(arg1) {
  return window['go']['service']['Store']['GetStore'](arg1);
}

export function SearchStoreList(arg1) {
  return window['go']['service']['Store']['SearchStoreList'](arg1);
}

export function UpdateStore(arg1, arg2, arg3) {
  return window['go']['service']['Store']['UpdateStore'](arg1, arg2, arg3);
}
