// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bo} from '../models';

export function CreateStore(arg1:string,arg2:string):Promise<bo.SimpleResp>;

export function DeleteStore(arg1:number):Promise<bo.SimpleResp>;

export function GetStore(arg1:number):Promise<bo.GetStoreResp>;

export function SearchStoreList(arg1:bo.SearchStoreReq):Promise<bo.SearchStoreResp>;

export function UpdateStore(arg1:number,arg2:string,arg3:string):Promise<bo.SimpleResp>;
