// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bo} from '../models';

export function GetUsageDetail(arg1:number):Promise<bo.GetDetailResp>;

export function SearchUsageList(arg1:bo.SearchUsageReq):Promise<bo.SearchUsageResp>;
