// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUsageDetail(arg1) {
  return window['go']['service']['Usage']['GetUsageDetail'](arg1);
}

export function SearchUsageList(arg1) {
  return window['go']['service']['Usage']['SearchUsageList'](arg1);
}
